---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/manifest-tool
    build_args:
    - VERSION=${DRONE_TAG:-1.0.0-rc3}
    tags: ${DRONE_TAG:-master}-amd64

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/manifest-tool
    build_args:
    - VERSION=${DRONE_TAG:-1.0.0-rc3}
    tags: ${DRONE_TAG:-master}-arm64

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-versioned
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    target: lansible/manifest-tool:${DRONE_TAG:-master}
    template: lansible/manifest-tool:${DRONE_TAG:-master}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
  when:
    branch:
    - master

- name: manifest-latest
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    target: lansible/manifest-tool:latest
    template: lansible/manifest-tool:${DRONE_TAG:-master}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
  when:
    event:
    - tag

depends_on:
- amd64
- arm64

trigger:
  branch:
  - master
